 # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@master
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.17
        with:
          name: gmadhok/porter-pipeline
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile:  ../../Dockerfile.tmpl
          registry: docker.pkg.github.com/gmadhok/porter-pipeline
